# Use the official Playwright Python image
FROM mcr.microsoft.com/playwright/python:v1.41.2-jammy

# Set the working directory in the container
WORKDIR /app

# Copy the scraping script into the container
COPY dags/kafka_stream.py /app/kafka_stream.py
COPY dags/static/prompt.py /app/prompt.py
COPY dags/utils/scrapping.py /app/scrapping.py
COPY dags/utils/utils.py /app/utils.py
# Install Python dependencies, ensure you have a requirements.txt file
COPY kafka-requirements.txt /app
RUN pip install --upgrade pip && pip install -r kafka-requirements.txt

RUN playwright install chromium --with-deps
# Command to run the script (adjust as necessary)
CMD ["python", "kafka_stream.py"]
